### ISSUE TITLE
Put the parsing part on a separate module

### ISSUE THREAD

**Issue by fbm-static** [zont/gulp-usemin#101]
Hey there. You have a really nice implementation here compared to usemin. I wish you could put the parsing part on a separate module so it could be used out of the stream context.

**Comment by tamlyn** [comment]
You can load just the parser from inside this package, e.g.:

    var blocksBuilder = require('gulp-usemin/lib/blocksBuilder');
    var blocks = blocksBuilder(file, options);

**Comment by fbm-static** [comment]
kewl!!!
