### ISSUE TITLE
Directory structure flattened

### ISSUE THREAD

**Issue by wulfsberg** [zont/gulp-usemin#105]
Given a directory structure like
`index.html`
`admin/other.html`

The command
```
gulp.task('minify', function () {
    return gulp.src('src/main/webapp/**/*.html')
        .pipe(usemin())
        .pipe(gulp.dest('target/webapp-min/'));
});
```
flattens the directory structure, writing both html files to target/webapp-min.

Version <=0.3.8 preserves the directory structure of the matched source files as expected.

Possible duplicate of #84 and regression of #8.

Duplicate of #99. Don't know why I didn't see that one when checking for known issues.

**Comment by ErikEvenson** [comment]
This seems to be happening again using 0.3.11.  I think you know that based on the comments in #94 though.

**Comment by wulfsberg** [comment]
#99 is logged against 0.3.11, so I'm just waiting for #100 to be pulled, and then I'll be a happy camper.

**Comment by yjaaidi** [comment]
Same issue here. This is broken since 0.3.9.

**Comment by andreialecu** [comment]
+1 anything past 0.3.8 is unusable for us because of this.
