### ISSUE TITLE
Data attributes on script tags in dist/index.html

### ISSUE THREAD

**Issue by jazzdragon** [zont/gulp-usemin#107]
I'm using require.js in my project, and to use it I have in my index.html this script tag:'
<script src="js/require.js" data-main="js/main"></script>

the data-main points require.js to my main.js file. I include this line in my build process that minifies require.js, but the data-main attributes gets lost. Is there a way to specify keeping an attribute?

**Comment by john-goldsmith** [comment]
+1

RequireJS needs a script tag like this:

`<script data-main="path/to/script" src="path/to/require.js"></script>`

However, running that through usemin will strip the `data-main` attribute.

**Comment by zont** [comment]
Duplicate #77
