### ISSUE TITLE
Two build:js - only one uglified

### ISSUE THREAD

**Issue by adyz** [zont/gulp-usemin#111]
Hi Guys, 

Great work with this gulp module! 

I have two JS blocks that I want minified
-- build:js js/bundle-1.js --
//Files here
-- endbuild --
-- build:js1 js/bundle-2.js --
//Other files here
-- endbuild --

First block generates uglified file, but second one is just concatenated.

Any ideas why?

Thanks, 
Adrian

**Comment by gera2ld** [comment]
I was also confused with this before. I think you should code like this:
``` javascript
.pipe(usemin({
    js:[...],
    js1:[...],
})
```
Actually there are developers hoping that pipes with the same id can be reused. #91

**Comment by gera2ld** [comment]
I was confused with this too. I think you should write your `gulpfile.js` like this:
``` javascript
.pipe(usemin({
    js:[...],
    js1:[...],
}));
```
Actually there are developers hoping that pipes with the same ids can be reused. #91

**Comment by adyz** [comment]
Ow, thanks a lot!
I think this bit should be added in the documentation too :dancer:

**Comment by hellfrom** [comment]
It would be great if this example has been added to documentation

**Comment by Amerr** [comment]
documentation have to be updated :+1:
