### ISSUE TITLE
Incorrect relative path for script in subfolder

### ISSUE THREAD

**Issue by wulfsberg** [zont/gulp-usemin#115]
Given the layout
```
src
	admin
		index.html
		script.js
```

and a script block in index.html like:
```
    <!-- build:js script-min.js -->
    <script src="script.js"></script>
    <!-- endbuild -->
```

The task
```
gulp.task('minify', function () {
  return gulp.src('src/**/*.html')
      .pipe(usemin({
        js: [uglify()]
      }))
      .pipe(gulp.dest('dest'));
});
```

produces a layout of
```
dest
	admin
		index.html
	script-min.js
```
but with index.html referencing `<script src="script-min.js"></script>`, i.e. expecting it in the same folder.

Forcing the script into the admin folder by using
```
    <!-- build:js admin/script-min.js -->
    <script src="script.js"></script>
    <!-- endbuild -->
```

produces a layout of
```
dest
	admin
		index.html
		script-min.js
```
		
but with index.html referencing `<script src="admin/script-min.js"></script>`, i.e. a level too deep.

This is a remnant of #99. (Thanks to @nick-pww for the fix so far).

**Comment by grayghostvisuals** [comment]
I've got the same issue. @zont What do you suggest as a workaround? Docs are extremely light and hard to decipher without written examples for the visually curious. Could you please assist?

**Comment by mikeobrien** [comment]
I think this might be related to #84. If so, same issue.

**Comment by dvankooijk** [comment]
Same issue. My workaround is with a find/replace, definitely not a good solution but works for now.
