### ISSUE TITLE
Does not appear to be using the output of gulp-minify-css or gulp-uglify

### ISSUE THREAD

**Issue by Nysosis** [zont/gulp-usemin#116]
Given this (partial) part of my build file

```javascript
var usemin = require('gulp-usemin');
var uglify = require('gulp-uglify');
var uglifyCss = require('gulp-minify-css');

gulp.task('usemin', function () {
  return gulp.src('src/index.html')
      .pipe(usemin({
        css: [uglifyCss(), 'concat'],
        js: [uglify()]
      }))
      .pipe(gulp.dest('dist'));
});
```

The generated js/css files are not minified. But have been concatenated down to the expected pipeline files.

Versions I'm using are as follows:
* Gulp: 3.8.11
* Gulp-Uglify: 1.2.0
* Gulp-Minify-Css: 0.3.13
* Gulp-Usemin: 0.3.11

**Comment by zont** [comment]
Cannot reproduce.
Please try it on gulp-usemin 0.3.14
