### ISSUE TITLE
using path with assetsDir breaks search path

### ISSUE THREAD

**Issue by konclave** [zont/gulp-usemin#123]
Dir structure: 
```
+- static
|    +- bower_components
|        +- ...
+- project
|    +- templates
|        index.html
|    gulpfile.js
```

block inside index.html:
```
<!-- build:js /static/scripts/vendor.min.js -->
<script src="/static/bower_components/jquery/dist/jquery.min.js"></script>
<!-- endbuild -->  
```

gulp task (running from project directory): 
```
gulp.src('templates/index.html')
    .pipe(plugins.usemin({
      path: '../',
      assetsDir: '../',
      js: [uglify()]
    }))
    .pipe(gulp.dest('templates/'));
```

expect usemin will read files form static/bower_components/... (according to path param), uglify them and write result to static/scripts/vendor.min.js (according to assetsDir param), then replace build:js block in index.html with <script src="/static/scripts/vendor.min.js"></script> (path from build:js block param) and will overwrite changed index.html

instead I've got an error: 
```
Path /static/bower_components/jquery/dist/jquery.min.js not found!
    at getFiles (/node_modules/gulp-usemin/lib/blocksBuilder.js:58:15)
```

if I remove assetsDir param, usemin finds files correctly, but writes result JS file relatively to index.html, as expected.

**Comment by konclave** [comment]
Did I miss the point of using assetsDir option? Is it not only root for result files? Why does it modifies the search path for source files?

**Comment by SkillyWeb** [comment]
Same problem for me : using my assets are not in the html/twig folder, so I use assetsDir. But when and only when I use assetsDir it modifies the search path and usemin didnt find js/css files.

**Comment by zont** [comment]
Fixed

**Comment by hyperbrave** [comment]
are we sure this is fixed?
