### ISSUE TITLE
`inlinecss` not working

### ISSUE THREAD

**Issue by oblador** [zont/gulp-usemin#129]
Copy pasting the example code using `build:inlinecss` results in a silent failure, adding a filename makes it working again. Sometimes, for example single page sites, it's preferable to inline CSS.

**Comment by zont** [comment]
Can you make test?

**Comment by oblador** [comment]
No, sorry don't have the time right now. Just think code copy pasted from the README should work, if not feel free to close this since I use another tool instead :-)
