### ISSUE TITLE
Build file but remove block section

### ISSUE THREAD

**Issue by ObjectiveTruth** [zont/gulp-usemin#134]
This is opposite to the goal of the project I think but is there a way to create a minified file from a block but have the block NOT be replaced by the final script tag?

Here's an example:

**BEFORE**

```html
<!-- build:minifiyJS js/minified.js -->
        <script src="unminified1.js"></script>
        <script src="unminified2.js"></script>
<!-- endbuild -->
```
**AFTER**

```html
<!-- Removed from html but file is created -->
```

I tried ```build:remove``` but it doesn't create the file

**Comment by ObjectiveTruth** [comment]
Couldn't find a way to do this, so I ended up using a little hacky solution incase anyone runs into the same issue:

use `gulp-inject` and inject nothing after `gulp-usemin`

```html
    <!-- inject:removeAfterBuild:js -->
            <!-- build:jsIonic js/ionic.min.js -->
                <!-- ionic/angularjs js -->
                <script src="vendors/ionic/js/ionic.bundle.min.js"></script>
                <script src="vendors/ngCordova/dist/ng-cordova.min.js"></script>
            <!-- endbuild -->
  <!-- endinject -->
```

**Comment by zont** [comment]
> Build file but remove block section
usemin is not designed for this.
