### ISSUE TITLE
Latest release - "Error: write after end"

### ISSUE THREAD

**Issue by klwemu** [zont/gulp-usemin#146]
It works with one file, but if you have more than:

stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^
Error: write after end
    at writeAfterEnd (C:\xampp\htdocs\vl-public\node_modules\gulp-minify-html\node_modules\thr
ough2\node_modules\readable-stream\lib\_stream_writable.js:144:12)

Current setup:
Node 4.1.2

    "gulp": "^3.9.0",
    "gulp-usemin": "^0.3.14",
    "gulp-rev": "~6.0.1",
    ....

  it does not depend if or if not other modules are used.

**Comment by zawilliams** [comment]
@klwemu - what did you do to resolve this issue?

**Comment by klwemu** [comment]
Hello, in my case the problem was that the first task was not really
finished when the 2.nd starts - although we have used runSequence
For me, runSequence is not a 100% solution. We changed to  ....


gulp.task('*build-dist*', function() {
    return gulp.src('app/**/*.html')
        .pipe(usemin({
        ...
        }))
        .pipe(gulp.dest('dist/'));
});
gulp.task('*build-dist-finishing*', ['*build-dist'*], function() {
    return gulp.src('dist/**/*.html')
        ...
});
gulp.task('*dist-serial*', ['*build-dist*', '*build-dist-finishing*']);



and then call:
   return runSequence(['*dist-serial*',  ...


That runs first *build-dist* and when finished  *build-dist-finishing*'

I hope it helps ...
Regards
Klaus

2015-10-27 21:29 GMT+01:00 Zach Williams <notifications@github.com>:

> @klwemu <https://github.com/klwemu> - what did you do to resolve this
> issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zont/gulp-usemin/issues/146#issuecomment-151634497>.
>



-- 

Klaus Muckenhuber
Business Developement

https://VISITLEAD.com
0049 7247 50315 - 11

**Comment by manuel-di-iorio** [comment]
This issue should not be closed because it hasn't been resolved, even in the latest release.
