### ISSUE TITLE
Error: "write after end" if you have more than 2 files

### ISSUE THREAD

**Issue by manuel-di-iorio** [zont/gulp-usemin#150]
Referring to this closed bug: https://github.com/zont/gulp-usemin/issues/146

I have the same issue and I think using another plugin like "runSequence" is only a workaround, this is a bug to resolve imho.

So, this is my complete task:

```
gulp.task('html', function() {
return gulp.src( ['../../raw_assets/views/**/*.+(html|php)'] )
        .pipe( watch(['../../raw_assets/views/**/*.+(html|php)']) )
        .pipe( debug() )
        .pipe( plumber() ) //error handler
        .pipe( usemin({
            outputRelativePath: "../../",
            html: [ minifyHTML() ],
            js: [ uglify() ]
        }) )
        .pipe( gulp.dest("../../app/views") )
        .pipe( browserSync.reload( {stream: true} ))
        .pipe( notify('HTML task complete!') );
});
```

My configuration:

```
node: v.5.0.0
gulp: v.3.9.0
gulp-usemin: v.0.3.14
```

So, when it tries to compile the first .php file does not show any error, but when tries with the second .php file, the error happens.
The .php files are not written to the disk, even the first.
note: the concatened.js file (an asset) instead is written.

**Comment by manuel-di-iorio** [comment]
**Update**

 if I remove from the usemin settings: `html: [ minifyHTML() ],`
..all works as expected, no errors and the .html and assets files are correctly written.

Obviously the bug is not resolved but at least I can simply use a workaround, minifying the .html files with `.pipe( minifyHTML()) )` instead of relegate this job to gulp-usemin itself.

Hope this can be useful to someone :)

**Comment by unlucio** [comment]
Same here running 0.3.16.
I can' believe the most of the people uses it with less than 2 file, we must be doing something wrong.
Any suggestion?

node: 4.2.2
gulp: 3.9.0
gulp-usemin: 0.3.16

**Comment by cstuncsik** [comment]
Same here with same version.

I used **glob** to read multiple files and **event-stream** to merge the gulp tasks

```javascript
import config from '../config.js';
import gulp from 'gulp';
import util from 'gulp-util';
import usemin from 'gulp-usemin';
import rev from 'gulp-rev';
import csso from 'gulp-csso';
import uglify from 'gulp-uglify';
import glob from 'glob';
import eventStream from 'event-stream';

gulp.task('html:prod', done => {
    glob(config.paths.builds.tmp.root + '*.html', function (err, files) {
        if (err) {
            done(err);
        }

        let tasks = files.map(file => {
            return gulp.src(file)
                .pipe(usemin({
                    css: [csso(), rev()],
                    js: [uglify(), rev()]
                }))
                .pipe(gulp.dest(config.paths.builds.prod.root))
                .on('error', util.log);
        });
        eventStream.merge(tasks).on('end', done);
    });
});
```

**Comment by pykiss** [comment]
Me too.

    return gulp.src('.tmp/*.html')
      .pipe(usemin({
        css: [minifyCss, rev],
        js: [ngAnnotate, uglify, rev],
        html: [minifyHtml({conditionals: true})]
      }))
      .pipe(gulp.dest('build/'))

**Comment by a-lian123** [comment]
Me too.
```
<!-- build:js ../js/common.min.js -->
    <script type="text/javascript" src="../js/common.js"></script>
<!-- endbuild -->
<!-- build:js ../js/index/page.index.min.js -->
    <script type="text/javascript" src="../js/index/page.index.js"></script>
<!-- endbuild -->
```
If i delete one pipeline, it work. But if it have two pipeline, it throw error: write after end

**Comment by Yathi** [comment]
I have the same problem too. 

`gulp.src('./app/index-new.html')` works but `gulp.src('./app/**/*.html')` does not work.

**Comment by ikenfin** [comment]
gulp-usemin 0.3.22, problem is still there

**Comment by oaleynik** [comment]
Workaround - wrap `minifyHtml` transform stream into function:

```javascript
html: [function () { return $.minifyHtml({empty: true}); }],
```

**Comment by ciro-maciel** [comment]
I have the same problem too.  I'm using the version "gulp-usemin": "^0.3.28",

And I managed to fix it as follows:

[**gulp 4.0**](https://github.com/gulpjs/gulp/blob/4.0/docs/README.md)
It has better control over the flow of tasks

[**gulp-foreach**](https://github.com/mariusGundersen/gulp-flatMap)
And use this component to the foreach in the src files

My task with **use-min** it is like this:

```
    return gulp.src('./compile/**/*.html')
        .pipe(foreach(function (stream, file) {
            return stream
                .pipe(usemin({
                    path: './compile/assets/',
                    outputRelativePath: '/assets/',
                    css: [minifyCss()],
                    // https://github.com/zont/gulp-usemin#usage
                    html: [function () {
                        // https://github.com/jonschlinkert/gulp-htmlmin
                        // https://github.com/kangax/html-minifier
                        return htmlmin({
                            html5: true,
                            collapseWhitespace: true,
                            removeComments: true,
                            removeEmptyAttributes: true,
                            removeRedundantAttributes: true,
                            collapseBooleanAttributes: true,
                            removeAttributeQuotes: true,
                            removeOptionalTags: true
                        });
                    }],
                    jsLibrary: [
                        uglify(uglifyConfig),
                        header(banner, {
                            pkg: pkg
                        })
                    ],
                    jsApp: [
                        // https://github.com/babel/gulp-babel
                        uglify(uglifyConfig),
                        header(banner, {
                            pkg: pkg
                        })
                    ],
                    inlinejs: [uglify()],
                    inlinecss: [minifyCss(), 'concat']
                }))
        }))
        .pipe(gulp.dest('./deploy/'));

```

**Comment by zont** [comment]
From README:

>If you need to call the same pipeline twice, you need to define each task as a function that returns the >stream object that should be used.
