### ISSUE TITLE
Replace html base tag

### ISSUE THREAD

**Issue by Starli0n** [zont/gulp-usemin#177]
Hi,

I was wondering if it was possible to replace the html base tag with your extension like:

````
<head>
    <!-- build:bs "/publish/" -->
    <base href="/public/" />
    <!-- endbuild -->
</head>
````

It seems that it does not work but maybe I do it wrong.
Thanks

**Comment by zont** [comment]
gulp-usemin replaces references to scripts or stylesheets only
