### ISSUE TITLE
how to add a script

### ISSUE THREAD

**Issue by JoveYu** [zont/gulp-usemin#183]
as what README say,

we can use `remove` to delete a script, so how to `add` a script or `replace` a script?

**Comment by GuyMograbi** [comment]
What do you mean? 

Writing something like

```
<!-- build:js lib1.js -->
<script src="some_file.js"></script>
<!-- endbuild --> 
```

Will replace `some_file.js` with `lib1.js`

Does this answer your question or did you mean another scenario?
