### ISSUE TITLE
Media query regex matches only first word

### ISSUE THREAD

**Issue by akempes** [zont/gulp-usemin#185]
Hi, I'm using this media query: 
```html
<!-- build:css styles/568.css -->
    <link rel="stylesheet" media="only screen and (min-width: 568px)" href="styles/568.css">
<!-- endbuild -->
```
After running gulp the media query will read just 'only'.  I removed the space in the `cssMediaReg` regex. It's working for me, but I don't know what the consequences are.

This is the updated regex:

```js
var cssMediaReg = /<\s*link\s+.*?media\s*=\s*['"]?([^'"]+).*?>/gi;
```

**Comment by zont** [comment]
Fixed by #186
