### ISSUE TITLE
ES6 support?

### ISSUE THREAD

**Issue by ashot-israelyan** [zont/gulp-usemin#195]
Hello all.

We are trying to minify our JS files which includes the new syntax of Javascript (ES6). We get a bunch of errors on arrow functions.

When we remove them, errors go away and the code minifies.

Is there a way to use es6 with your plugin?

Thanks in advance.

**Comment by sapics** [comment]
Yes you can! Please try [gulp-terser](https://www.npmjs.com/package/gulp-terser) instead of `gulp-uglify`.
