### ISSUE TITLE
CSS attributes

### ISSUE THREAD

**Issue by atomtigerzoo** [zont/gulp-usemin#199]
I am in need of adding - or just keeping them - attributes to my CSS link tags like so:

    <link rel="stylesheet" data-name="value" href="styles.css">

Usemin overwrites the whole tag with its own version but I want to keep my attributes.

I know there is an option for adding attributes to JS tags, but what about CSS tags? Or why does usemin just keep all attributes on the tags?

**Comment by zont** [comment]
gulp-usemin is deprecated. Please dont use it. Use Rollup, Webpack, Browserify, Parcel and other
