### ISSUE TITLE
Decouple build paths of HTML template and compiled asset

### ISSUE THREAD

**Issue by mzgajner** [zont/gulp-usemin#37]
I have a HTML template file placed in a random internal location (wherever the framework decides it stores templates). My publicly visible web folder is stored elsewhere.

Because of this structure, I have a few problems to overcome. In the template, I define blocks normally:

``` html
<!-- build:js js/lib.js -->
```

The path in this block is the path I want to appear in the processed HTML file, but gulp-usemin assumes that the processed JS file should also be stored according to this path, relative to my HTML template. This is not the case.

To give a more literal example, these steps are needed:
- a template in `/project-source/templates/dev/template.html` needs to compile to `/project-source/templates/prod/template.html`
- JS assets in `/public-html/uncompiled-js/*.js` need to compile to `/public-html/js/compiled.js`
- reference in the compiled template needs to point to `/js/compiled.js`

I think this a pretty common use case, since frameworks can often store their templates somewhere different than the static JS/CSS files. Is there a way to configure gulp-usemin to achieve what I want?

**Comment by dgwaldo** [comment]
@mzgajner Just made this branch for use in a build process at work, added ability decouple bundle and build path, as well as ability to add an async tag.
