### ISSUE TITLE
Gulp add src?

### ISSUE THREAD

**Issue by drewhamlett** [zont/gulp-usemin#46]
I'm trying to concat my templates to the end of my main script file.  This is what I have so far.  Doesn't seem to be working but I'm sure I'm doing something wrong.  I'm using gulp-add-src.  I've also tried just using gulp.src since you can add midstream now.

``` js
gulp.task('usemin', function () {

    return gulp.src('./app/index.html')
        .pipe($.usemin({
            css: [$.minifyCss(), 'concat', $.rev()],
            js: [
                $.addSrc('./build/templates.js'),
                'concat',
                $.ngmin(),
                $.uglify(),
                $.rev()
            ],
            vendor: [$.uglify(), $.rev()]
        }))
        .pipe(gulp.dest(config.dist));
});
```

**Comment by allenhwkim** [comment]
+1 having the same issue. I wish there is a smarter way to add template cache for production only.
