### ISSUE TITLE
Async attribute

### ISSUE THREAD

**Issue by limonte** [zont/gulp-usemin#52]
It would be great to have ability to add async attribute to script tag generated by gulp-usemin. 

It's often very useful: https://developers.google.com/web/fundamentals/performance/critical-rendering-path/adding-interactivity-with-javascript#parser-blocking-vs-asynchronous-javascript

**Comment by craigmdennis** [comment]
+1

**Comment by Snugug** [comment]
:+1:

**Comment by sbley** [comment]
+1

**Comment by sohamkamani** [comment]
Just a suggestion - we could have these attributes as an object passed inside the build task,

for example : 

```js
var jsAttributes = {
  async : true,
  'some-other-attribute' : 'some-value'
  };
gulp.task('usemin', function() {
  return gulp.src('./*.html')
    .pipe(usemin({
      css: [ rev() ],
      html: [ minifyHtml({ empty: true }) ],
      js: [ uglify(), rev() ],
      jsAttributes: jsAttributes,
      inlinejs: [ uglify() ],
      inlinecss: [ minifyCss(), 'concat' ]
    }))
    .pipe(gulp.dest('build/'));
});
```
would give you 
```html
<script src="build.js" async some-other-attribute="some-value"></script>
```
I guess this would solve #75 and #77 as well.

Thoughts?
