### ISSUE TITLE
gulp-rev: rev() is not working for css

### ISSUE THREAD

**Issue by rakeshrawatg** [zont/gulp-usemin#61]
rev() is not working for css in following manner, even its not generating the css files.

// build-css-usemin: concat css files using HTML comments
gulp.task('build-css-usemin', ['build-sass-to-css'], function() {
    return gulp.src(yeoman.prod.path.temp.basePath + '/indexGulp.html')
	.pipe(usemin({
        css: ['concat', rev()]
    }))
  	.pipe(gulp.dest(yeoman.prod.path.temp.basePath))
});

**Comment by zont** [comment]
Cannot reproduce bug. All working correct
