### ISSUE TITLE
Do not work with gulp-size

### ISSUE THREAD

**Issue by pauldijou** [zont/gulp-usemin#65]
I wanted to use `gulp-usemin` with [gulp-size](https://www.npmjs.org/package/gulp-size) in order to see the before / after of the minification, using something like:

~~~ javascript
gulp.task('usemin', ['deploy:clean', 'build'], function () {
  return gulp.src(['./index.html'], {base: './'})
    .pipe($.usemin({
      css: [$.size({title: 'CSS before'}), $.minifyCss(), 'concat', $.rev(), $.size({title: 'CSS after'})]
    }))
    .pipe(gulp.dest($.paths.deploy.dest));
});
~~~

But it looks like it does not work. All files are processed inside the `gulp-size` plugin but the final output isn't display. The [flush function](https://github.com/sindresorhus/gulp-size/blob/a0c65772a519cd11abbf9f89f73b0974c3c21c7a/index.js#L47-L55) of the stream isn't called for an unknown reason to me. Maybe the stream isn't correctly closed...

**Comment by zont** [comment]
Async tasks support added
