### ISSUE TITLE
Stylus not parsing

### ISSUE THREAD

**Issue by bholben** [zont/gulp-usemin#71]
`gulp-usemin` is parsing Less correctly, but it is not parsing Stylus with the code below...

    var gulp    = require('gulp'),
        less    = require('gulp-less'),
        stylus  = require('gulp-stylus'),
        usemin  = require('gulp-usemin');

    gulp.task('usemin', function() {
        return gulp.src('src/index.html')
        .pipe(usemin({
            less: [less()],
            stylus: [stylus()]
        }))
        .pipe(gulp.dest('dist/'));
    });

**Comment by zont** [comment]
Fixed
