### ISSUE TITLE
Multiple search path includes all matching files

### ISSUE THREAD

**Issue by tamlyn** [zont/gulp-usemin#83]
I have the following files

    src/app.js
    .tmp/app.js

and block

    
    <script src="app.js"></script>
    

I've set up express to server files from both `.tmp` and `src` so that it takes the first available. I would expect usemin to do the same but what it actually does is concat both `app.js` files. 

A simple (and probably advisable) workaround is to rename one of the files (e.g. `.tmp/app.compiled.js`). Nonetheless I spent a while scratching my head over it and the current behaviour seems incorrect so I thought it was worth flagging.

**Comment by zont** [comment]
Please, use another plugin for this
