### ISSUE TITLE
Compiled files are written relative to the base directory of the file being scanned

### ISSUE THREAD

**Issue by seth2810** [zont/gulp-usemin#84]
Hi, dear creators of the library. So far I have used in my toolbox grunt-usemin, which when saving files that were specified in the tag build as the base directory using the current directory where the process is started (process.cwd ()). In your own version of the library there assetsDir, path and outputRelativePath, which frankly erred user wants to use your library. I quote the following tag in my views/login.html:

  <script src="/vendor/postmessage/postmessage.js"></script>
  <script src="/scripts/pibble/login.js"></script>

It would be desirable that the files were sought in the following path {.tmp/public, assets}/scripts/login.js and stored in the same path, where they were found, i.e, {.tmp/public, assets} /scripts/login-revhash.js, rather than the views/scripts/login-revhash.js

I think what has changed to an error #8 were made hastily, because this problem (#8) is solved by specifying the base property, that was described in the last comment.

**Comment by mikeobrien** [comment]
If I'm understanding this issue correctly, I'm running into the same thing. This used to work but no longer does with the latest bits. So if I have the following layout:

```
/
    /wwwroot
        index.html
        some.js
```

With an html block of:

```html
<!-- build:js bundle.js -->
<script src="some.js" type="text/javascript"></script>
<!-- endbuild -->
```

And I do the following:

```js
gulp.task('bundle', function () {
  return gulp.src('*/index.html', { base: '.' })
          .pipe(usemin({
              css: [ minifyCss, 'concat', rev() ],
              js: [ removeBom(), 'concat', uglify(), rev() ]
          }))
          .pipe(gulp.dest('.'));
});
```

The `index.html` gets updated properly but the generated files are created relative to the root, not the `index.html` as they were before:

```
/
    bundle.js <-- This is in the wrong folder, should be in wwwroot
    /wwwroot
        index.html
        some.js
```

**Comment by zont** [comment]
Fixed
