### ISSUE TITLE
Does all pipelines have to be unique? How to reuse pipelines for different blocks?

### ISSUE THREAD

**Issue by ev45ive** [zont/gulp-usemin#91]
build:js /script/vendors.js
endbuild 
build:js /script/script.js 
endbuild 

-- such thing with gulp 3.8.10 and gulp-rev 2.0.1 produces strange results, like : 

scripts-50e8cdb8-50e8cdb8-50e8cdb8-50e8cdb8.js 

more info:
https://github.com/sindresorhus/gulp-rev/issues/80

I've fixed it but ended up with very bad looking task:
```
    return gulp.src(['./app/index.html'])
        .pipe($.replace('<!-- #templates -->', '<script src="scripts/templates.min.js"></script>'))
        .pipe($.usemin({
            // there apparently cannot be two pipes (builds) with same name
            ie: [$.rev()],
            jsvendor: [$.rev()],
            js: [$.ngAnnotate(), $.rev()],
            templates: [$.ngAnnotate(), $.rev()],
            cssvendor: [
                // rewrite paths from source to compiled directories
                $.minifyCss(),
                // FIX paths in CSS - AFTER MINIFICATION ( gulp error )
                $.replace('/bower_components/sass-bootstrap/fonts/','/fonts/'),
                $.replace('images/images/','images/'),
                $.replace('app/images/','images/'),
                $.rev(),
            ],
            css: [
                // rewrite paths from source to compiled directories
                $.minifyCss(),
                // FIX paths in CSS - AFTER MINIFICATION ( gulp error )
                $.replace('/bower_components/sass-bootstrap/fonts/','/fonts/'),
                $.replace('images/images/','images/'),
                $.replace('app/images/','images/'),
                $.rev(),
            ]
        }))
```
Why cant I just have many "JS" blocks like I did before with gulp-usemin and grunt usemin? 
how to avoid it / solve it better?

**Comment by zont** [comment]
Yes, pipelineid unique.
Not possible to make many "JS" blocks with different content and one pipeline: pipeline executing async and if we send to it different blocks then on end of pipeline we cannot understand for whose is the result.

**Comment by pizthewiz** [comment]
Is this also true when processing multiple files? The README offers this usage example:
```javascript
gulp.task('usemin', function () {
  return gulp.src('./*.html')
      .pipe(usemin({
        css: [minifyCss(), 'concat'],
        html: [minifyHtml({empty: true})],
        js: [uglify(), rev()]
      }))
      .pipe(gulp.dest('build/'));
});
```

but if there were multiple HTML files, each pulling in common CSS or JS libs, say:
```HTML
<!-- build:css css/lib.css -->
<link rel="stylesheet" href="bower_components/normalize.css/normalize.css">
<!-- endbuild -->
```
this would blow up too, no?

**Comment by greaterweb** [comment]
> Yes, pipelineid unique.

@zont this was not always the case. Seems to be a new requirement of 0.3.11?

Am I correct to assume that by closing it you don't consider it to be a bug?

**Comment by greaterweb** [comment]
For clarity purposes, are you are saying we can no longer do this? 

```html
<!-- build:js /data/js/app.js -->
<script src="js/lib.js"></script>
<script src="js/main.js"></script>
<!-- endbuild -->

<!-- build:js /data/js/app-2.js -->
<script src="js/lib.js"></script>
<script src="js/main.js"></script>
<!-- endbuild -->
```

As noted, this type of functionality had previously worked so it's a bit of a bummer that it no longer does. It's an easy enough work around I suppose but I've got a number of projects setup using the same sort of shared pipelineId approach.

**Comment by greaterweb** [comment]
Digging around a bit, bf06486bd7a667d496e4db384de19f6166f2bb26 appears to be the last commit with the feature working as desired. I'll peak around 29e7ccc56dde98aff285ea367ab1518f7c8be284 to see where the problem may have been introduced.

**Comment by greaterweb** [comment]
I've made a little bit of sense about where to look to fix this but need some help sorting it out further.  Not as well versed with streams as I'd like otherwise I may be able to work through a solution.

Looking at lines [#89](https://github.com/zont/gulp-usemin/blob/25b7fb976646c8ee4295784a8164fd4622b6c4bd/lib/blocksBuilder.js#L89) `lib/blocksBuilder.js`) and [#97](https://github.com/zont/gulp-usemin/blob/25b7fb976646c8ee4295784a8164fd4622b6c4bd/lib/blocksBuilder.js#L97), the tasks for each pipeline are passed by reference. 

The task values become modified in [`lib/pipeline.js`](https://github.com/zont/gulp-usemin/blob/25b7fb976646c8ee4295784a8164fd4622b6c4bd/lib/pipeline.js#L8-L17). This doesn't really pose a problem if there are unique instances of a pipeline but when they are referenced multiple times it keeps getting padded out.

Locally I tried modifying `lib/blocksBuilder.js` to pass the arrays by value:

```js

        if (jsReg.test(section[5])) {
          blocks.push({
            type: 'js',
            nameInHTML: section[3],
            name: section[4],
            files: getFiles(section[5], jsReg, section[2]),
            tasks: options[section[1]].slice(0)
          });
        } else {
          blocks.push({
            type: 'css',
            nameInHTML: section[3],
            name: section[4],
            files: getFiles(section[5], cssReg, section[2]),
            tasks: options[section[1]].slice(0),
            mediaQuery: cssMediaQuery
          });
        }
```

This gives me the correct task length in `lib/pipeline.js` but I now get an error:

```shell

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: write after end
    at writeAfterEnd (/my-project/node_modules/gulp-uglify/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:144:12)
    at DestroyableTransform.Writable.write (/my-project/node_modules/gulp-uglify/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:192:5)
    at Stream.ondata (stream.js:51:26)
    at Stream.EventEmitter.emit (events.js:95:17)
    at Stream.endStream (/my-project/node_modules/gulp-usemin/node_modules/gulp-concat/index.js:90:10)
    at _end (/my-project/node_modules/gulp-usemin/node_modules/gulp-concat/node_modules/through/index.js:65:9)
    at Stream.stream.end (/my-project/node_modules/gulp-usemin/node_modules/gulp-concat/node_modules/through/index.js:74:5)
    at Transform.onend (/my-project/node_modules/gulp-usemin/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:523:10)
    at Transform.g (events.js:180:16)
    at Transform.EventEmitter.emit (events.js:117:20)

```

I get the overall flow of the app but apparently I'm not well versed enough on streams to button everything up.

@zont, any thoughts?

**Comment by pizthewiz** [comment]
@greaterweb yup, that is the same backlog as if you tried to process multiple files. Strange that the README usage would specify `gulp.src('./*.html')` if it really couldn't handle multiple files…

**Comment by zont** [comment]
Yes, it is a bug.

**Comment by chrisjansky** [comment]
Confirming that reverting back to 0.3.9 fixes this temporarily. Also, styles minification using gulp-autoprefixer@2.0.1 and gulp-minify-css@0.4.2 stopped working and reverting back to 2.0.0 and 0.3.11 for these plugins respectively seems to have fixed it.

**Comment by wurmr** [comment]
I had to revert back to 0.3.8 to fix it for me.  0.3.9 seems to be the version that brought `async tasks support` which seems to be what broke it.

**Comment by fotofinder** [comment]
.
(just to support)

**Comment by cgwyllie** [comment]
+1 seeing this problem, revert to 0.3.8 fixed for me too.

**Comment by lihaibh** [comment]
When im trying to compile multiple html files i receive this erorr:
  throw er; // Unhandled stream error in pipe.

I changed gulp-usemin to version 0.3.8, it doesnt show me the error now but it compiles only 1 file.
What should we do about this? its very serious bug.

**Comment by ryanlelek** [comment]
Fellow Google travelers...
What worked for me:
(Uses the latest gulp-usemin v0.3.11 and gulp-foreach v0.1.0)

Gulp ForEach:
https://github.com/mariusGundersen/gulp-forEach
```
gulp.task('your-regular-task', function () {
  return gulp.src('src/*.html')
    // 1) Move your Code that was HERE
    // New Module
    .pipe(foreach(function (stream, file) {
      return stream
        // 2) Move to here
        .pipe(usemin({
          html    : [minify_html({ quotes : true, empty : true })],
          css_app : [minify_css({ keepSpecialComments : 1 }), 'concat'],
          js_app  : [minify_js(), 'concat']
        }))
        // BE CAREFUL!!!
        // This now has the CSS/JS files added to the stream
        // Not just the HTML files you sourced
        .pipe(gulp.dest('build/'));
    }))
});
```

**Comment by grayghostvisuals** [comment]
@ryanlelek That's a sweet solution :+1:  I'm still not sure if it is the “best” because I'm no expert on this, but it does in fact work like you said if others need verification. I'm still finding problems w/sub directory files containing build blocks as I state in the stackoverflow question linked in my referencing issue above.

**Comment by ryanlelek** [comment]
@grayghostvisuals 

Did that new release fix it for you?
If so, can you share the part of the gulpfile that you changed?
Right now the docs on the project README.md shows how to replace one task/transformation, but not multiple.
```
html: [ minifyHtml({ empty: true }) ],
// turns into
html: [ function () {return minifyHtml({ empty: true });} ],
```
I tried wrapping all of my tasks in a no-op function () { return <step>; } but that didnt work well at all to turn the single step into a multi step.

Thoughts @zont? I can open a new issue if you prefer.

**Comment by p30arena** [comment]
@ryanlelek solution worked for me +1

**Comment by grayghostvisuals** [comment]
@ryanlelek This is the current way I'm handling things [https://github.com/grayghostvisuals/transformicons/blob/master/gulpfile.js#L149-L161](https://github.com/grayghostvisuals/transformicons/blob/master/gulpfile.js#L149-L161)

**Comment by p30arena** [comment]
@grayghostvisuals @ryanlelek I placed the last pipe after the first pipe, but you placed it after the second pipe, is there a problem with that?

```
gulp.task('usemin', ['templates', 'enable-production'], function() {
  return gulp.src(['app/index.html', 'app/badbrowser.html'])
    .pipe(foreach(function (stream, file) {
      return stream.pipe($.usemin({
        html: [$.minifyHtml({empty: true})],
        js: ['concat', $.ngAnnotate(), $.uglify({outSourceMap: false})],
        css: ['concat', $.minifyCss({compatibility: true, keepBreaks: true})]
      }));
    }))
    .pipe(gulp.dest('dist'));
});
```

**Comment by ryanlelek** [comment]
@p30arena It has been quite a while since I looked at this, but from what I understood, there are two points (and take these with a grain of salt):

#1) The pipe outside as you have it, instead of after, usemin, worked on the non-minified source files
#2) The inside pipe "forked" for each file minified

Since you're just using it to save the output file, you should be ok, especially if you're already getting the results you want. I'd recommend checking the output files in dist/ to see if it has any effect in your particular circumstances.
