### ISSUE TITLE
Processed html files written to wrong location.

### ISSUE THREAD

**Issue by nick-pww** [zont/gulp-usemin#99]
With 0.3.11 we are seeing issues with the output of the the processed html (jsp files in our case) being written to the wrong locations. I'm not sure if this is the same as https://github.com/zont/gulp-usemin/issues/84 but I think it's a bit different.

Sample task:

gulp.task('usemin', ['scripts'], function () {
	return gulp.src('src/main/webapp/**/*.jsp')
//Don't like all the extra pipelines, but is a new 'requirement'
			.pipe(usemin({
				cssLib: [minifyCss()],
				cssApp: [minifyCss()],
				jsLib: [uglify()],
				jsApp: [ngmin(), uglify()]
			}))
			.pipe(gulp.dest('target/gulp-sample-1.0-SNAPSHOT/'));
});

All of the JSP files that processed all end up in target/gulp-sample-1.0-SNAPSHOT/ and not in the subdirectory they were found in. So, if we have:
src/main/webapp/app/index.jsp
it gets written to:
target/gulp-sample-1.0-SNAPSHOT/index.jsp

I've tracked down the issue to htmlBuilder and will have a pull request shortly, but want to make sure we aren't doing anything obviously wrong here. Everything I see in the code says it currently has no other way to act, so not sure what we can do differently.

**Comment by zont** [comment]
Fixed
